# Generated by Django 3.0.5 on 2020-04-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Kateg',
            field=models.ManyToManyField(help_text='Додати статю до категорії', to='catalog.Kateg'),
        ),
    ]
